# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # `yarn install`
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test # Runs `yarn test` => Jest runner
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: cy:open # `yarn cy:open` => Cypress e2e Runner
